### ISSUE TITLE
Cannot load 57-60 Undead Mage guide due to parse issues

### ISSUE THREAD

**Issue by lukeknoot** [lukeknoot/classicwow-to-guidelime#28]
Steps to reproduce:
- Try to load 57-60 Undead Mage guide

Result:
- "Parsing guide "Guide": zone not found in code [G 35.0, 85.3 Blackrock Depths] in like "246...
![dM3suXl](https://user-images.githubusercontent.com/6252715/68401267-905a9380-01cd-11ea-86f4-26c1db05b49a.png)

Expected result:
- Loads successfully

**Comment by JasonDal** [comment]
Same happens with 59-60 warlock - guidelime doesnt recognise BRD as a zone
