### ISSUE TITLE
Guidelime_GnomeWarlock\32-37.lua Spelling error - not loading

### ISSUE THREAD

**Issue by Mogwong** [lukeknoot/classicwow-to-guidelime#42]
Line 194
`Fly to [F Southshore] [G 55.5,47.7 Ironfroge]`

Change to
`Fly to [F Southshore] [G 55.5,47.7 Ironforge]`

Thanks for the great guide! It's super helpful.

P.S. If changing using the in-game editor, the line is 192.

**Comment by lukeknoot** [comment]
Thanks for reporting!

Just pushed a fix for this. I'll have to do another release for this to show up in the guides but for now people can follow your use the in-game editor as you've described.
